version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-starter-app
    ports:
      - 3001:3001
    volumes:
      - .:/app
    environment:
      - PORT=${PORT}
      - MONGODB=${MONGODB}
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: node-starter-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongodb_data:
